using System;


/* Class automatically generated by MVVM Light Toolkit. Not used. */
namespace TreasureHuntDesktopApplication.FullClient.Design
{
    public class DesignDataService 
    {
      
    }
}