//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureHuntDesktopApplication.FullClient.TreasureHuntService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="question", Namespace="http://schemas.datacontract.org/2004/07/TreasureHuntDesktopApplication.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class question : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Question1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QuestionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntquestion[] huntquestionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question1 {
            get {
                return this.Question1Field;
            }
            set {
                this.Question1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QuestionId {
            get {
                return this.QuestionIdField;
            }
            set {
                this.QuestionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                this.URLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntquestion[] huntquestions {
            get {
                return this.huntquestionsField;
            }
            set {
                this.huntquestionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="huntquestion", Namespace="http://schemas.datacontract.org/2004/07/TreasureHuntDesktopApplication.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class huntquestion : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HuntIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HuntQuestionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QuestionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt huntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt> huntReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question questionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question> questionReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HuntId {
            get {
                return this.HuntIdField;
            }
            set {
                this.HuntIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HuntQuestionId {
            get {
                return this.HuntQuestionIdField;
            }
            set {
                this.HuntQuestionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QuestionId {
            get {
                return this.QuestionIdField;
            }
            set {
                this.QuestionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt hunt {
            get {
                return this.huntField;
            }
            set {
                this.huntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt> huntReference {
            get {
                return this.huntReferenceField;
            }
            set {
                this.huntReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question question {
            get {
                return this.questionField;
            }
            set {
                this.questionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question> questionReference {
            get {
                return this.questionReferenceField;
            }
            set {
                this.questionReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="hunt", Namespace="http://schemas.datacontract.org/2004/07/TreasureHuntDesktopApplication.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class hunt : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HuntDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HuntIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HuntNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntparticipant[] huntparticipantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntquestion[] huntquestionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userhunt[] userhuntsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HuntDescription {
            get {
                return this.HuntDescriptionField;
            }
            set {
                this.HuntDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HuntId {
            get {
                return this.HuntIdField;
            }
            set {
                this.HuntIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HuntName {
            get {
                return this.HuntNameField;
            }
            set {
                this.HuntNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntparticipant[] huntparticipants {
            get {
                return this.huntparticipantsField;
            }
            set {
                this.huntparticipantsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntquestion[] huntquestions {
            get {
                return this.huntquestionsField;
            }
            set {
                this.huntquestionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userhunt[] userhunts {
            get {
                return this.userhuntsField;
            }
            set {
                this.userhuntsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="huntparticipant", Namespace="http://schemas.datacontract.org/2004/07/TreasureHuntDesktopApplication.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class huntparticipant : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ElapsedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HuntIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HuntParticipantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TallyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt huntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt> huntReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user> userReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ElapsedTime {
            get {
                return this.ElapsedTimeField;
            }
            set {
                this.ElapsedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HuntId {
            get {
                return this.HuntIdField;
            }
            set {
                this.HuntIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HuntParticipantId {
            get {
                return this.HuntParticipantIdField;
            }
            set {
                this.HuntParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                this.StartTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Tally {
            get {
                return this.TallyField;
            }
            set {
                this.TallyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt hunt {
            get {
                return this.huntField;
            }
            set {
                this.huntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt> huntReference {
            get {
                return this.huntReferenceField;
            }
            set {
                this.huntReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user> userReference {
            get {
                return this.userReferenceField;
            }
            set {
                this.userReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userhunt", Namespace="http://schemas.datacontract.org/2004/07/TreasureHuntDesktopApplication.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class userhunt : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HuntIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserHuntIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserRoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt huntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt> huntReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user> userReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole userroleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole> userroleReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HuntId {
            get {
                return this.HuntIdField;
            }
            set {
                this.HuntIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserHuntId {
            get {
                return this.UserHuntIdField;
            }
            set {
                this.UserHuntIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserRoleId {
            get {
                return this.UserRoleIdField;
            }
            set {
                this.UserRoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt hunt {
            get {
                return this.huntField;
            }
            set {
                this.huntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt> huntReference {
            get {
                return this.huntReferenceField;
            }
            set {
                this.huntReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user> userReference {
            get {
                return this.userReferenceField;
            }
            set {
                this.userReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole userrole {
            get {
                return this.userroleField;
            }
            set {
                this.userroleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole> userroleReference {
            get {
                return this.userroleReferenceField;
            }
            set {
                this.userroleReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user", Namespace="http://schemas.datacontract.org/2004/07/TreasureHuntDesktopApplication.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class user : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntparticipant[] huntparticipantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userhunt[] userhuntsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole[] userrolesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyPassword {
            get {
                return this.CompanyPasswordField;
            }
            set {
                this.CompanyPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntparticipant[] huntparticipants {
            get {
                return this.huntparticipantsField;
            }
            set {
                this.huntparticipantsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userhunt[] userhunts {
            get {
                return this.userhuntsField;
            }
            set {
                this.userhuntsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole[] userroles {
            get {
                return this.userrolesField;
            }
            set {
                this.userrolesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="role", Namespace="http://schemas.datacontract.org/2004/07/TreasureHuntDesktopApplication.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class role : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole[] userrolesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole[] userroles {
            get {
                return this.userrolesField;
            }
            set {
                this.userrolesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userrole", Namespace="http://schemas.datacontract.org/2004/07/TreasureHuntDesktopApplication.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class userrole : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserRoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.role roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.role> roleReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user> userReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userhunt[] userhuntsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserRoleId {
            get {
                return this.UserRoleIdField;
            }
            set {
                this.UserRoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.role role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.role> roleReference {
            get {
                return this.roleReferenceField;
            }
            set {
                this.roleReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user> userReference {
            get {
                return this.userReferenceField;
            }
            set {
                this.userReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userhunt[] userhunts {
            get {
                return this.userhuntsField;
            }
            set {
                this.userhuntsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TreasureHuntService.ITreasureHuntService")]
    public interface ITreasureHuntService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/SaveQuestion", ReplyAction="http://tempuri.org/ITreasureHuntService/SaveQuestionResponse")]
        long SaveQuestion(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question newQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/SaveQuestion", ReplyAction="http://tempuri.org/ITreasureHuntService/SaveQuestionResponse")]
        System.Threading.Tasks.Task<long> SaveQuestionAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question newQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/SaveNewHuntQuestion", ReplyAction="http://tempuri.org/ITreasureHuntService/SaveNewHuntQuestionResponse")]
        void SaveNewHuntQuestion(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntquestion huntQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/SaveNewHuntQuestion", ReplyAction="http://tempuri.org/ITreasureHuntService/SaveNewHuntQuestionResponse")]
        System.Threading.Tasks.Task SaveNewHuntQuestionAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntquestion huntQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/SaveNewHunt", ReplyAction="http://tempuri.org/ITreasureHuntService/SaveNewHuntResponse")]
        long SaveNewHunt(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt newHunt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/SaveNewHunt", ReplyAction="http://tempuri.org/ITreasureHuntService/SaveNewHuntResponse")]
        System.Threading.Tasks.Task<long> SaveNewHuntAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt newHunt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetHuntQuestions", ReplyAction="http://tempuri.org/ITreasureHuntService/GetHuntQuestionsResponse")]
        long[] GetHuntQuestions(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt hunt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetHuntQuestions", ReplyAction="http://tempuri.org/ITreasureHuntService/GetHuntQuestionsResponse")]
        System.Threading.Tasks.Task<long[]> GetHuntQuestionsAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt hunt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetTreasureHunts", ReplyAction="http://tempuri.org/ITreasureHuntService/GetTreasureHuntsResponse")]
        TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt[] GetTreasureHunts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetTreasureHunts", ReplyAction="http://tempuri.org/ITreasureHuntService/GetTreasureHuntsResponse")]
        System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt[]> GetTreasureHuntsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetQuestion", ReplyAction="http://tempuri.org/ITreasureHuntService/GetQuestionResponse")]
        TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question GetQuestion(long questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetQuestion", ReplyAction="http://tempuri.org/ITreasureHuntService/GetQuestionResponse")]
        System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question> GetQuestionAsync(long questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/UpdateQuestion", ReplyAction="http://tempuri.org/ITreasureHuntService/UpdateQuestionResponse")]
        void UpdateQuestion(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question updatedQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/UpdateQuestion", ReplyAction="http://tempuri.org/ITreasureHuntService/UpdateQuestionResponse")]
        System.Threading.Tasks.Task UpdateQuestionAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question updatedQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetHuntBasedOnName", ReplyAction="http://tempuri.org/ITreasureHuntService/GetHuntBasedOnNameResponse")]
        TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt GetHuntBasedOnName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetHuntBasedOnName", ReplyAction="http://tempuri.org/ITreasureHuntService/GetHuntBasedOnNameResponse")]
        System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt> GetHuntBasedOnNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetExistingUsers", ReplyAction="http://tempuri.org/ITreasureHuntService/GetExistingUsersResponse")]
        TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user[] GetExistingUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetExistingUsers", ReplyAction="http://tempuri.org/ITreasureHuntService/GetExistingUsersResponse")]
        System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user[]> GetExistingUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/SaveUser", ReplyAction="http://tempuri.org/ITreasureHuntService/SaveUserResponse")]
        long SaveUser(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/SaveUser", ReplyAction="http://tempuri.org/ITreasureHuntService/SaveUserResponse")]
        System.Threading.Tasks.Task<long> SaveUserAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/SaveUserRole", ReplyAction="http://tempuri.org/ITreasureHuntService/SaveUserRoleResponse")]
        void SaveUserRole(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole newUserRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/SaveUserRole", ReplyAction="http://tempuri.org/ITreasureHuntService/SaveUserRoleResponse")]
        System.Threading.Tasks.Task SaveUserRoleAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole newUserRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetUser", ReplyAction="http://tempuri.org/ITreasureHuntService/GetUserResponse")]
        TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user GetUser(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetUser", ReplyAction="http://tempuri.org/ITreasureHuntService/GetUserResponse")]
        System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user> GetUserAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetUserRole", ReplyAction="http://tempuri.org/ITreasureHuntService/GetUserRoleResponse")]
        TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole GetUserRole(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetUserRole", ReplyAction="http://tempuri.org/ITreasureHuntService/GetUserRoleResponse")]
        System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole> GetUserRoleAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/SaveUserHunt", ReplyAction="http://tempuri.org/ITreasureHuntService/SaveUserHuntResponse")]
        void SaveUserHunt(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userhunt userHunt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/SaveUserHunt", ReplyAction="http://tempuri.org/ITreasureHuntService/SaveUserHuntResponse")]
        System.Threading.Tasks.Task SaveUserHuntAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userhunt userHunt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetTreasureHuntsForParticularUser", ReplyAction="http://tempuri.org/ITreasureHuntService/GetTreasureHuntsForParticularUserResponse" +
            "")]
        TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt[] GetTreasureHuntsForParticularUser(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetTreasureHuntsForParticularUser", ReplyAction="http://tempuri.org/ITreasureHuntService/GetTreasureHuntsForParticularUserResponse" +
            "")]
        System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt[]> GetTreasureHuntsForParticularUserAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetHuntParticipants", ReplyAction="http://tempuri.org/ITreasureHuntService/GetHuntParticipantsResponse")]
        TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntparticipant[] GetHuntParticipants(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt currentTreasureHunt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetHuntParticipants", ReplyAction="http://tempuri.org/ITreasureHuntService/GetHuntParticipantsResponse")]
        System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntparticipant[]> GetHuntParticipantsAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt currentTreasureHunt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetParticipantName", ReplyAction="http://tempuri.org/ITreasureHuntService/GetParticipantNameResponse")]
        TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user GetParticipantName(long participant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/GetParticipantName", ReplyAction="http://tempuri.org/ITreasureHuntService/GetParticipantNameResponse")]
        System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user> GetParticipantNameAsync(long participant);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITreasureHuntServiceChannel : TreasureHuntDesktopApplication.FullClient.TreasureHuntService.ITreasureHuntService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TreasureHuntServiceClient : System.ServiceModel.ClientBase<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.ITreasureHuntService>, TreasureHuntDesktopApplication.FullClient.TreasureHuntService.ITreasureHuntService {
        
        public TreasureHuntServiceClient() {
        }
        
        public TreasureHuntServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TreasureHuntServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TreasureHuntServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TreasureHuntServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long SaveQuestion(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question newQuestion) {
            return base.Channel.SaveQuestion(newQuestion);
        }
        
        public System.Threading.Tasks.Task<long> SaveQuestionAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question newQuestion) {
            return base.Channel.SaveQuestionAsync(newQuestion);
        }
        
        public void SaveNewHuntQuestion(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntquestion huntQuestion) {
            base.Channel.SaveNewHuntQuestion(huntQuestion);
        }
        
        public System.Threading.Tasks.Task SaveNewHuntQuestionAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntquestion huntQuestion) {
            return base.Channel.SaveNewHuntQuestionAsync(huntQuestion);
        }
        
        public long SaveNewHunt(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt newHunt) {
            return base.Channel.SaveNewHunt(newHunt);
        }
        
        public System.Threading.Tasks.Task<long> SaveNewHuntAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt newHunt) {
            return base.Channel.SaveNewHuntAsync(newHunt);
        }
        
        public long[] GetHuntQuestions(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt hunt) {
            return base.Channel.GetHuntQuestions(hunt);
        }
        
        public System.Threading.Tasks.Task<long[]> GetHuntQuestionsAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt hunt) {
            return base.Channel.GetHuntQuestionsAsync(hunt);
        }
        
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt[] GetTreasureHunts() {
            return base.Channel.GetTreasureHunts();
        }
        
        public System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt[]> GetTreasureHuntsAsync() {
            return base.Channel.GetTreasureHuntsAsync();
        }
        
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question GetQuestion(long questionId) {
            return base.Channel.GetQuestion(questionId);
        }
        
        public System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question> GetQuestionAsync(long questionId) {
            return base.Channel.GetQuestionAsync(questionId);
        }
        
        public void UpdateQuestion(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question updatedQuestion) {
            base.Channel.UpdateQuestion(updatedQuestion);
        }
        
        public System.Threading.Tasks.Task UpdateQuestionAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.question updatedQuestion) {
            return base.Channel.UpdateQuestionAsync(updatedQuestion);
        }
        
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt GetHuntBasedOnName(string name) {
            return base.Channel.GetHuntBasedOnName(name);
        }
        
        public System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt> GetHuntBasedOnNameAsync(string name) {
            return base.Channel.GetHuntBasedOnNameAsync(name);
        }
        
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user[] GetExistingUsers() {
            return base.Channel.GetExistingUsers();
        }
        
        public System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user[]> GetExistingUsersAsync() {
            return base.Channel.GetExistingUsersAsync();
        }
        
        public long SaveUser(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user newUser) {
            return base.Channel.SaveUser(newUser);
        }
        
        public System.Threading.Tasks.Task<long> SaveUserAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user newUser) {
            return base.Channel.SaveUserAsync(newUser);
        }
        
        public void SaveUserRole(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole newUserRole) {
            base.Channel.SaveUserRole(newUserRole);
        }
        
        public System.Threading.Tasks.Task SaveUserRoleAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole newUserRole) {
            return base.Channel.SaveUserRoleAsync(newUserRole);
        }
        
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user GetUser(string emailAddress) {
            return base.Channel.GetUser(emailAddress);
        }
        
        public System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user> GetUserAsync(string emailAddress) {
            return base.Channel.GetUserAsync(emailAddress);
        }
        
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole GetUserRole(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user user) {
            return base.Channel.GetUserRole(user);
        }
        
        public System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userrole> GetUserRoleAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user user) {
            return base.Channel.GetUserRoleAsync(user);
        }
        
        public void SaveUserHunt(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userhunt userHunt) {
            base.Channel.SaveUserHunt(userHunt);
        }
        
        public System.Threading.Tasks.Task SaveUserHuntAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.userhunt userHunt) {
            return base.Channel.SaveUserHuntAsync(userHunt);
        }
        
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt[] GetTreasureHuntsForParticularUser(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user user) {
            return base.Channel.GetTreasureHuntsForParticularUser(user);
        }
        
        public System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt[]> GetTreasureHuntsForParticularUserAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user user) {
            return base.Channel.GetTreasureHuntsForParticularUserAsync(user);
        }
        
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntparticipant[] GetHuntParticipants(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt currentTreasureHunt) {
            return base.Channel.GetHuntParticipants(currentTreasureHunt);
        }
        
        public System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.huntparticipant[]> GetHuntParticipantsAsync(TreasureHuntDesktopApplication.FullClient.TreasureHuntService.hunt currentTreasureHunt) {
            return base.Channel.GetHuntParticipantsAsync(currentTreasureHunt);
        }
        
        public TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user GetParticipantName(long participant) {
            return base.Channel.GetParticipantName(participant);
        }
        
        public System.Threading.Tasks.Task<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.user> GetParticipantNameAsync(long participant) {
            return base.Channel.GetParticipantNameAsync(participant);
        }
    }
}
